// gen_paths.go 是 Path SSOT 的 codegen 工具。
//
// 它读取 MKPSE_presets/tools/paths.yaml 作为单一真相来源（SSOT），
// 生成两个文件：
//   - mkp-supporte/internal/paths/generated.go
//   - mkp-publisher/frontend/src/generated/paths.ts
//
// 为了零外部依赖（不引入 yaml 库），本工具直接用字符串模板生成固定内容。
// paths.yaml 的内容是已知常量，若修改 paths.yaml，需要同步更新本文件的模板。
//
// 用法：
//
//	go run MKPSE_presets/tools/gen_paths.go
//
// 从仓库根目录或任意子目录运行均可。
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// generatedGoContent 是 generated.go 的完整内容。
// 与 paths.yaml 中的常量保持一致。
const generatedGoContent = `// Code generated by tools/gen_paths.go — DO NOT EDIT

package paths

import "path/filepath"

// Preset 根目录
const (
	PresetRootMKP  = "presets/mkp"
	PresetRootBBS  = "presets/bbs"
	PresetRootOrca = "presets/orca"
)

// 各 type 保存子路径（相对于 preset root）
const (
	SavePathBBSMachine  = "machine"
	SavePathBBSProcess  = "process"
	SavePathOrcaMachine = "machine"
	SavePathOrcaProcess = "process"
)

// Content 文件相对路径
const (
	ContentFileMachineCatalog = "content/machine_catalog.json"
	ContentFileParamRegistry  = "content/param_registry.json"
	ContentFileFAQ            = "content/faq.json"
	ContentFileAbout          = "content/about.json"
	ContentFileLayoutSchema   = "content/layout_schema.json"
	ContentFileChangelog      = "content/changelog.json"
	ContentFileModelCopy      = "content/model_copy.json"
)

// URL 前缀（用于生成下载 URL）
const (
	URLPrefixMKP  = "/presets/mkp"
	URLPrefixBBS  = "/presets/bbs"
	URLPrefixOrca = "/presets/orca"
)

// ===== Builder 函数 =====

// MKPPresetURL 构造 mkp_toml 的下载 URL，如 "/presets/mkp/A1.toml"
func MKPPresetURL(fileName string) string {
	return URLPrefixMKP + "/" + fileName
}

// BBSMachineURL 构造 bbs_machine 的下载 URL
func BBSMachineURL(subPath string, fileName string) string {
	if subPath == "" {
		return URLPrefixBBS + "/" + SavePathBBSMachine + "/" + fileName
	}
	return URLPrefixBBS + "/" + SavePathBBSMachine + "/" + subPath + "/" + fileName
}

// BBSProcessURL 构造 bbs_process 的下载 URL
func BBSProcessURL(subPath string, fileName string) string {
	if subPath == "" {
		return URLPrefixBBS + "/" + SavePathBBSProcess + "/" + fileName
	}
	return URLPrefixBBS + "/" + SavePathBBSProcess + "/" + subPath + "/" + fileName
}

// OrcaMachineURL 构造 orca_machine 的下载 URL
func OrcaMachineURL(subPath string, fileName string) string {
	if subPath == "" {
		return URLPrefixOrca + "/" + SavePathOrcaMachine + "/" + fileName
	}
	return URLPrefixOrca + "/" + SavePathOrcaMachine + "/" + subPath + "/" + fileName
}

// OrcaProcessURL 构造 orca_process 的下载 URL
func OrcaProcessURL(subPath string, fileName string) string {
	if subPath == "" {
		return URLPrefixOrca + "/" + SavePathOrcaProcess + "/" + fileName
	}
	return URLPrefixOrca + "/" + SavePathOrcaProcess + "/" + subPath + "/" + fileName
}

// MKPPresetPath 构造 mkp_toml 的本地保存路径（相对路径），如 "presets/mkp/A1.toml"
func MKPPresetPath(fileName string) string {
	return filepath.Join(PresetRootMKP, fileName)
}

// BBSMachineSavePath 构造 bbs_machine 的本地保存路径
func BBSMachineSavePath(subPath string, fileName string) string {
	if subPath == "" {
		return filepath.Join(PresetRootBBS, SavePathBBSMachine, fileName)
	}
	return filepath.Join(PresetRootBBS, SavePathBBSMachine, subPath, fileName)
}

// BBSProcessSavePath 构造 bbs_process 的本地保存路径
func BBSProcessSavePath(subPath string, fileName string) string {
	if subPath == "" {
		return filepath.Join(PresetRootBBS, SavePathBBSProcess, fileName)
	}
	return filepath.Join(PresetRootBBS, SavePathBBSProcess, subPath, fileName)
}

// OrcaMachineSavePath 构造 orca_machine 的本地保存路径
func OrcaMachineSavePath(subPath string, fileName string) string {
	if subPath == "" {
		return filepath.Join(PresetRootOrca, SavePathOrcaMachine, fileName)
	}
	return filepath.Join(PresetRootOrca, SavePathOrcaMachine, subPath, fileName)
}

// OrcaProcessSavePath 构造 orca_process 的本地保存路径
func OrcaProcessSavePath(subPath string, fileName string) string {
	if subPath == "" {
		return filepath.Join(PresetRootOrca, SavePathOrcaProcess, fileName)
	}
	return filepath.Join(PresetRootOrca, SavePathOrcaProcess, subPath, fileName)
}

// ContentFilePath 返回 content 文件的相对路径
func ContentFilePath(key string) string {
	switch key {
	case "machine_catalog":
		return ContentFileMachineCatalog
	case "param_registry":
		return ContentFileParamRegistry
	case "faq":
		return ContentFileFAQ
	case "about":
		return ContentFileAbout
	case "layout_schema":
		return ContentFileLayoutSchema
	case "changelog":
		return ContentFileChangelog
	case "model_copy":
		return ContentFileModelCopy
	default:
		return ""
	}
}
`

// pathsTSContent 是 paths.ts 的完整内容。
// 使用 {{BT}} 作为反引号占位符（TS 模板字符串语法），写入前替换为真实反引号。
const pathsTSContent = `// Code generated by tools/gen_paths.go — DO NOT EDIT

// Preset 根目录
export const PRESET_ROOT_MKP = "presets/mkp"
export const PRESET_ROOT_BBS = "presets/bbs"
export const PRESET_ROOT_ORCA = "presets/orca"

// 各 type 保存子路径
export const SAVE_PATH_BBS_MACHINE = "machine"
export const SAVE_PATH_BBS_PROCESS = "process"
export const SAVE_PATH_ORCA_MACHINE = "machine"
export const SAVE_PATH_ORCA_PROCESS = "process"

// Content 文件相对路径
export const CONTENT_FILE_MACHINE_CATALOG = "content/machine_catalog.json"
export const CONTENT_FILE_PARAM_REGISTRY = "content/param_registry.json"
export const CONTENT_FILE_FAQ = "content/faq.json"
export const CONTENT_FILE_ABOUT = "content/about.json"
export const CONTENT_FILE_LAYOUT_SCHEMA = "content/layout_schema.json"
export const CONTENT_FILE_CHANGELOG = "content/changelog.json"
export const CONTENT_FILE_MODEL_COPY = "content/model_copy.json"

// URL 前缀
export const URL_PREFIX_MKP = "/presets/mkp"
export const URL_PREFIX_BBS = "/presets/bbs"
export const URL_PREFIX_ORCA = "/presets/orca"

// ===== Builder 函数 =====

export function mkpPresetURL(fileName: string): string {
  return {{BT}}${URL_PREFIX_MKP}/${fileName}{{BT}}
}

export function bbsMachineURL(subPath: string, fileName: string): string {
  if (subPath === "") {
    return {{BT}}${URL_PREFIX_BBS}/${SAVE_PATH_BBS_MACHINE}/${fileName}{{BT}}
  }
  return {{BT}}${URL_PREFIX_BBS}/${SAVE_PATH_BBS_MACHINE}/${subPath}/${fileName}{{BT}}
}

export function bbsProcessURL(subPath: string, fileName: string): string {
  if (subPath === "") {
    return {{BT}}${URL_PREFIX_BBS}/${SAVE_PATH_BBS_PROCESS}/${fileName}{{BT}}
  }
  return {{BT}}${URL_PREFIX_BBS}/${SAVE_PATH_BBS_PROCESS}/${subPath}/${fileName}{{BT}}
}

export function orcaMachineURL(subPath: string, fileName: string): string {
  if (subPath === "") {
    return {{BT}}${URL_PREFIX_ORCA}/${SAVE_PATH_ORCA_MACHINE}/${fileName}{{BT}}
  }
  return {{BT}}${URL_PREFIX_ORCA}/${SAVE_PATH_ORCA_MACHINE}/${subPath}/${fileName}{{BT}}
}

export function orcaProcessURL(subPath: string, fileName: string): string {
  if (subPath === "") {
    return {{BT}}${URL_PREFIX_ORCA}/${SAVE_PATH_ORCA_PROCESS}/${fileName}{{BT}}
  }
  return {{BT}}${URL_PREFIX_ORCA}/${SAVE_PATH_ORCA_PROCESS}/${subPath}/${fileName}{{BT}}
}

// 按 type 分发 URL 构造
export function buildPresetURL(type: string, fileName: string, subPath: string = ""): string {
  switch (type) {
    case "mkp_toml":
      return mkpPresetURL(fileName)
    case "bbs_machine":
      return bbsMachineURL(subPath, fileName)
    case "bbs_process":
      return bbsProcessURL(subPath, fileName)
    case "orca_machine":
      return orcaMachineURL(subPath, fileName)
    case "orca_process":
      return orcaProcessURL(subPath, fileName)
    default:
      return mkpPresetURL(fileName)
  }
}
`

// findRepoRoot 从当前工作目录向上查找，直到找到 MKPSE_presets/tools/paths.yaml。
func findRepoRoot() string {
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatalf("无法获取当前工作目录: %v", err)
	}
	dir := cwd
	for {
		marker := filepath.Join(dir, "MKPSE_presets", "tools", "paths.yaml")
		if _, err := os.Stat(marker); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			log.Fatalf("无法找到 MKPSE_presets/tools/paths.yaml，请从 MKPSE_redo 仓库内运行（当前目录: %s）", cwd)
		}
		dir = parent
	}
}

// ensureDir 确保目录存在，不存在则创建。
func ensureDir(dir string) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Fatalf("无法创建目录 %s: %v", dir, err)
	}
}

// writeFile 写入文件内容。
func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		log.Fatalf("无法写入文件 %s: %v", path, err)
	}
}

func main() {
	repoRoot := findRepoRoot()

	// 校验 paths.yaml 存在（SSOT 文件）
	yamlPath := filepath.Join(repoRoot, "MKPSE_presets", "tools", "paths.yaml")
	if _, err := os.Stat(yamlPath); err != nil {
		log.Fatalf("paths.yaml 不存在: %s: %v", yamlPath, err)
	}
	fmt.Printf("✓ SSOT 文件: %s\n", yamlPath)

	// 目标文件路径
	goOutDir := filepath.Join(repoRoot, "mkp-supporte", "internal", "paths")
	goOutFile := filepath.Join(goOutDir, "generated.go")
	tsOutDir := filepath.Join(repoRoot, "mkp-publisher", "frontend", "src", "generated")
	tsOutFile := filepath.Join(tsOutDir, "paths.ts")

	// 确保目录存在
	ensureDir(goOutDir)
	ensureDir(tsOutDir)

	// 写入 generated.go
	writeFile(goOutFile, generatedGoContent)
	fmt.Printf("✓ 生成 Go 常量: %s\n", goOutFile)

	// 写入 paths.ts（替换反引号占位符）
	tsContent := strings.ReplaceAll(pathsTSContent, "{{BT}}", "`")
	writeFile(tsOutFile, tsContent)
	fmt.Printf("✓ 生成 TS 常量: %s\n", tsOutFile)

	fmt.Println("\nPath SSOT codegen 完成。")
}
